# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.35.1
# 

Name:       harbour-powermanga

# >> macros
# << macros

Summary:    An arcade 2D shoot-em-up game
Version:    0.93.1
Release:    0
Group:      Games
License:    GPLv3+
URL:        https://github.com/brunonymous/Powermanga
Source0:    %{name}-%{version}.tar.gz
Source100:  harbour-powermanga.yaml
BuildRequires:  pkgconfig(sdl2)
BuildRequires:  pkgconfig(SDL2_mixer)
BuildRequires:  pkgconfig(SDL2_ttf)
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(wayland-egl)
BuildRequires:  cmake
BuildRequires:  extra-cmake-modules
BuildRequires:  desktop-file-utils
BuildRequires:  fdupes

%description
Powermanga is an arcade 2D shoot-em-up game with 41 levels and more
than 200 sprites.

%if "%{?vendor}" == "chum"
Type: desktop-application
DeveloperName: TLK Games
PackagedBy: nephros
Categories:
 - Game
 - Arcade
Custom:
  Repo: %{url}
  PackagingRepo: https://github.com/nephros/Powermanga
PackageIcon: %{url}/master/icons/%{name}.svg
Screenshots:
  - https://libregamewiki.org/images/4/43/Powermanga_linux1.png
%endif


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
#export CFLAGS="${CFLAGS} -DPOWERMANGA_HANDHELD_CONSOLE"
#export CFLAGS="${CFLAGS} -DPREFIX=\"%%{_prefix}\""
# << build pre

%cmake .  \
    -DPOWERMANGA_SDL=ON \
    -DPOWERMANGA_SDL2=ON \
    -DUSE_SDLMIXER=ON


# >> build post
cmake --build . --config Release
# << build post

%install
# >> install pre
install -Dpm755 powermanga %{buildroot}%{_bindir}/%{name}
install -d %{buildroot}%{_datadir}/%{name}
cp -r data     %{buildroot}%{_datadir}/%{name}/
cp -r texts    %{buildroot}%{_datadir}/%{name}/
cp -r sounds   %{buildroot}%{_datadir}/%{name}/
cp -r graphics %{buildroot}%{_datadir}/%{name}/
# << install pre

# >> install post
install -Dpm644 powermanga.desktop %{buildroot}%{_datadir}/applications/%{name}.desktop
install -Dpm644 images_for_menu_entry/powermanga.48.png %{buildroot}%{_datadir}/icons/hicolor/48x48/apps/%{name}.png
printf '\n[X-Sailjail]\nApplicationName=powermanga\nOrganizationName=tlk-games\nPermissions=Sensors;Audio\n' >> %{buildroot}%{_datadir}/applications/%{name}.desktop
find %{buildroot}%{_datadir}/%{name}/ \
-name Makefile.am \
-exec rm {} \;
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%fdupes  %{buildroot}/%{_datadir}/%{name}

%files
%license COPYING
%{_bindir}/*
%{_datadir}/applications/*.desktop
%{_datadir}/icons/*/*/apps/*
%dir %{_datadir}/%{name}
%{_datadir}/%{name}/*
%exclude %{_datadir}/%{name}/sounds/*.zik
# >> files
# << files
